/* tslint:disable */
/* eslint-disable */
/**
 * API for user admin panel
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * Contact: korotkov.ivan.s@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 *
 * @export
 * @interface NewUser
 */
export interface NewUser {
  /**
   *
   * @type {string}
   * @memberof NewUser
   */
  name: string;
  /**
   *
   * @type {string}
   * @memberof NewUser
   */
  phone: string;
  /**
   *
   * @type {string}
   * @memberof NewUser
   */
  email: string;
  /**
   * We have more than 2 options for genders as some users won\'t be comfortable specifying their gender, and some users define themselves as non-binary
   * @type {string}
   * @memberof NewUser
   */
  gender: NewUserGenderEnum;
}

/**
 * @export
 * @enum {string}
 */
export enum NewUserGenderEnum {
  Male = "male",
  Female = "female",
  Other = "other",
  Unspecified = "unspecified",
}
